logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  acp:
    default-provider: codex

llm:
  model-selection:
    default-model:
      model: gpt-5.2-codex
      provider: codex
    by-agent-type:
      commit-agent:
        model: gpt-5.1-codex-mini
        provider: codex
      merge-conflict-agent:
        model: gpt-5.1-codex-mini
        provider: codex
      ai-filter:
        model: gpt-5.1-codex-mini
        provider: codex
    by-template: {}

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
