logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  chat-model:
    provider: acp
  acp:
    default-provider: codex
    providers:
      codex:
        transport: stdio
        command: ${ACP_COMMAND:codex-acp}
        args: ${ACP_ARGS:--sandbox danger-full-access --ask-for-approval never --yolo true}
        working-directory: ${ACP_WORKING_DIR:}
        auth-method: chatgpt
#        env:
#          PATH:

llm:
  model-selection:
    default-model: gpt-5.2-codex
    by-agent-type:
      commit-agent: gpt-5.1-codex-mini
      merge-conflict-agent: gpt-5.1-codex-mini
      ai-filter: gpt-5.1-codex-mini
    by-template: {}

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
