logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  chat-model.provider: acp
  acp:
    default-provider: ${ACP_PROVIDER:codex}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
