logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  acp:
    default-provider: claudeopenrouter

llm:
  model-selection:
    default-model:
      model: openai/gpt-oss-120b
      provider: claude_openrouter
    by-agent-type:
      commit-agent:
        model: google/gemini-3.1-flash-lite
        provider: claude_openrouter
      merge-conflict-agent:
        model: google/gemini-3.1-flash-lite
        provider: claude_openrouter
      ai-filter:
        model: google/gemini-3.1-flash-lite
        provider: claude_openrouter
    by-template: {}

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
