logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  acp:
    default-provider: claude_llama

llm:
  model-selection:
    default-model:
      model: gpt-oss:120b-cloud
      provider: claude_llama
    by-agent-type:
      commit-agent:
        model: gpt-oss:120b-cloud
        provider: claude_llama
      merge-conflict-agent:
        model: gpt-oss:120b-cloud
        provider: claude_llama
      ai-filter:
        model: gpt-oss:120b-cloud
        provider: claude_llama
    by-template: {}

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
